
version: '3'

env:
  PORT: 8000
tasks:
  build:server:
    desc: "Build the server binary"
    cmds:
      - go build -o bin/ cmd/uno/*.go

  run:server:
    desc: "Run the server"
    cmds:
      - bin/main

  run:client:
    desc: "Run the client"
    cmds:
      - wscat -c ws://localhost:8080/ws