
version: '3'

tasks:
  build:server:
    desc: "Build the server binary"
    cmds:
      - if [ "$(go env GOOS)" = "windows" ]; then
        go build -o bin/server.exe cmd/uno/*.go;
        else
        go build -o bin/server cmd/uno/*.go;
        fi

  run:server:
    desc: "Run the server"
    cmds:
      - if [ "$(go env GOOS)" = "windows" ]; then
        bin/server.exe;
        else
        bin/server;
        fi
    deps:
      - build:server

  run:client:
    desc: "Run the client"
    cmds:
      - wscat -c ws://localhost:8080/ws